export const SUI_NETWORK = (process.env.NEXT_PUBLIC_SUI_NETWORK ?? 'testnet') as
  | 'testnet'
  | 'mainnet'
  | 'devnet';

export const SUI_STREAM_PACKAGE_ID =
  process.env.NEXT_PUBLIC_SUI_STREAM_PACKAGE ?? '';

export const SUI_STREAM_PACKAGE_ORIGINAL_ID =
  process.env.NEXT_PUBLIC_SUI_STREAM_PACKAGE_ORIGINAL ??
  SUI_STREAM_PACKAGE_ID;

export const SUI_STREAM_MODULE = 'clip';

export const SUI_CLOCK_OBJECT_ID = '0x6';

export const WALRUS_PUBLISHER_URL =
  process.env.NEXT_PUBLIC_WALRUS_PUBLISHER_URL ??
  'https://publisher.walrus-testnet.walrus.space';

export const WALRUS_AGGREGATOR_URL =
  process.env.NEXT_PUBLIC_WALRUS_AGGREGATOR_URL ??
  'https://aggregator.walrus-testnet.walrus.space';

export const DEFAULT_WALRUS_EPOCHS = 5;

export const CLIP_CREATED_EVENT_TYPE = SUI_STREAM_PACKAGE_ORIGINAL_ID
  ? `${SUI_STREAM_PACKAGE_ORIGINAL_ID}::${SUI_STREAM_MODULE}::ClipCreated`
  : '';

export const CLIP_VIEWED_EVENT_TYPE = SUI_STREAM_PACKAGE_ORIGINAL_ID
  ? `${SUI_STREAM_PACKAGE_ORIGINAL_ID}::${SUI_STREAM_MODULE}::ClipViewed`
  : '';

export const SUI_STREAM_ACCESS_MODULE = 'access';

export const CLIP_UNLOCKED_EVENT_TYPE = SUI_STREAM_PACKAGE_ORIGINAL_ID
  ? `${SUI_STREAM_PACKAGE_ORIGINAL_ID}::${SUI_STREAM_ACCESS_MODULE}::ClipUnlocked`
  : '';

export const CLIP_ACCESS_TYPE = SUI_STREAM_PACKAGE_ORIGINAL_ID
  ? `${SUI_STREAM_PACKAGE_ORIGINAL_ID}::${SUI_STREAM_ACCESS_MODULE}::ClipAccess`
  : '';

export const SUI_STREAM_VOTE_PACKAGE_ID =
  process.env.NEXT_PUBLIC_SUI_STREAM_VOTE_PACKAGE ?? SUI_STREAM_PACKAGE_ID;

export const SUI_STREAM_SUBSCRIBE_PACKAGE_ID =
  process.env.NEXT_PUBLIC_SUI_STREAM_SUBSCRIBE_PACKAGE ?? SUI_STREAM_PACKAGE_ID;

export const SUBSCRIBED_EVENT_TYPE = SUI_STREAM_SUBSCRIBE_PACKAGE_ID
  ? `${SUI_STREAM_SUBSCRIBE_PACKAGE_ID}::${SUI_STREAM_MODULE}::Subscribed`
  : '';

export const UNSUBSCRIBED_EVENT_TYPE = SUI_STREAM_SUBSCRIBE_PACKAGE_ID
  ? `${SUI_STREAM_SUBSCRIBE_PACKAGE_ID}::${SUI_STREAM_MODULE}::Unsubscribed`
  : '';

export const VOTE_CAST_EVENT_TYPE = SUI_STREAM_VOTE_PACKAGE_ID
  ? `${SUI_STREAM_VOTE_PACKAGE_ID}::${SUI_STREAM_MODULE}::VoteCast`
  : '';

export const VOTE_REMOVED_EVENT_TYPE = SUI_STREAM_VOTE_PACKAGE_ID
  ? `${SUI_STREAM_VOTE_PACKAGE_ID}::${SUI_STREAM_MODULE}::VoteRemoved`
  : '';

export const VOTE_OBJECT_TYPE = SUI_STREAM_VOTE_PACKAGE_ID
  ? `${SUI_STREAM_VOTE_PACKAGE_ID}::${SUI_STREAM_MODULE}::Vote`
  : '';

export const VOTE_UPVOTE = 1;
export const VOTE_DOWNVOTE = 2;

export const SUI_STREAM_COMMENT_PACKAGE_ID =
  process.env.NEXT_PUBLIC_SUI_STREAM_COMMENT_PACKAGE ?? SUI_STREAM_PACKAGE_ID;

export const COMMENT_CREATED_EVENT_TYPE = SUI_STREAM_COMMENT_PACKAGE_ID
  ? `${SUI_STREAM_COMMENT_PACKAGE_ID}::${SUI_STREAM_MODULE}::CommentCreated`
  : '';

export const COMMENT_DELETED_EVENT_TYPE = SUI_STREAM_COMMENT_PACKAGE_ID
  ? `${SUI_STREAM_COMMENT_PACKAGE_ID}::${SUI_STREAM_MODULE}::CommentDeleted`
  : '';

export function computeViewRequiredSeconds(durationSeconds: number): number {
  if (!Number.isFinite(durationSeconds) || durationSeconds <= 0) {
    return CAMPAIGN_VIEW_REQUIRED_SECONDS;
  }
  const adaptive = Math.max(3, Math.floor(durationSeconds * 0.8));
  return Math.min(CAMPAIGN_VIEW_REQUIRED_SECONDS, adaptive);
}

export const COMMENT_OBJECT_TYPE = SUI_STREAM_COMMENT_PACKAGE_ID
  ? `${SUI_STREAM_COMMENT_PACKAGE_ID}::${SUI_STREAM_MODULE}::Comment`
  : '';

export const MAX_COMMENT_WORDS = 500;

export const SUI_STREAM_DONATE_PACKAGE_ID =
  process.env.NEXT_PUBLIC_SUI_STREAM_DONATE_PACKAGE ?? SUI_STREAM_PACKAGE_ID;

export const DONATION_SENT_EVENT_TYPE = SUI_STREAM_PACKAGE_ORIGINAL_ID
  ? `${SUI_STREAM_PACKAGE_ORIGINAL_ID}::${SUI_STREAM_MODULE}::DonationSent`
  : '';

export const DONATION_SENT_V2_EVENT_TYPE = SUI_STREAM_PACKAGE_ORIGINAL_ID
  ? `${SUI_STREAM_PACKAGE_ORIGINAL_ID}::${SUI_STREAM_MODULE}::DonationSentV2`
  : '';

const DEFAULT_SEAL_KEY_SERVERS_TESTNET = [
  '0x73d05d62c18d9374e3ea529e8e0ed6161da1a141a94d3f76ae3fe4e99356db75',
  '0xf5d14a81a982144ae441cd7d64b09027f116a468bd36e7eca494f750591623c8',
];

export const SEAL_KEY_SERVERS = (
  process.env.NEXT_PUBLIC_SEAL_KEY_SERVERS ??
  DEFAULT_SEAL_KEY_SERVERS_TESTNET.join(',')
)
  .split(',')
  .map((id) => id.trim())
  .filter(Boolean);

export const SEAL_THRESHOLD = Number(
  process.env.NEXT_PUBLIC_SEAL_THRESHOLD ?? '2'
);

export const SEAL_SESSION_TTL_MIN = 30;
export const SEAL_ID_BYTES = 32;
export const MIST_PER_SUI = 1_000_000_000;

export const SUI_STREAM_CAMPAIGN_MODULE = 'campaign';

export const SUI_STREAM_CAMPAIGN_PACKAGE_ID =
  process.env.NEXT_PUBLIC_SUI_STREAM_CAMPAIGN_PACKAGE ?? SUI_STREAM_PACKAGE_ID;

export const SUI_STREAM_CAMPAIGN_ORIGINAL_ID =
  process.env.NEXT_PUBLIC_SUI_STREAM_CAMPAIGN_ORIGINAL ??
  SUI_STREAM_CAMPAIGN_PACKAGE_ID;

export const CAMPAIGN_CREATED_EVENT_TYPE = SUI_STREAM_CAMPAIGN_ORIGINAL_ID
  ? `${SUI_STREAM_CAMPAIGN_ORIGINAL_ID}::${SUI_STREAM_CAMPAIGN_MODULE}::CampaignCreated`
  : '';

export const CAMPAIGN_TOGGLED_EVENT_TYPE = SUI_STREAM_CAMPAIGN_ORIGINAL_ID
  ? `${SUI_STREAM_CAMPAIGN_ORIGINAL_ID}::${SUI_STREAM_CAMPAIGN_MODULE}::CampaignToggled`
  : '';

export const CAMPAIGN_REWARD_CLAIMED_EVENT_TYPE = SUI_STREAM_CAMPAIGN_ORIGINAL_ID
  ? `${SUI_STREAM_CAMPAIGN_ORIGINAL_ID}::${SUI_STREAM_CAMPAIGN_MODULE}::RewardClaimed`
  : '';

export const CAMPAIGN_EXHAUSTED_EVENT_TYPE = SUI_STREAM_CAMPAIGN_ORIGINAL_ID
  ? `${SUI_STREAM_CAMPAIGN_ORIGINAL_ID}::${SUI_STREAM_CAMPAIGN_MODULE}::CampaignExhausted`
  : '';

export const CAMPAIGN_WITHDRAWN_EVENT_TYPE = SUI_STREAM_CAMPAIGN_ORIGINAL_ID
  ? `${SUI_STREAM_CAMPAIGN_ORIGINAL_ID}::${SUI_STREAM_CAMPAIGN_MODULE}::CampaignWithdrawn`
  : '';

export const CAMPAIGN_OBJECT_TYPE = SUI_STREAM_CAMPAIGN_ORIGINAL_ID
  ? `${SUI_STREAM_CAMPAIGN_ORIGINAL_ID}::${SUI_STREAM_CAMPAIGN_MODULE}::Campaign`
  : '';

export const MISSION_VIEW_BIT = 1;
export const MISSION_LIKE_BIT = 2;
export const MISSION_COMMENT_BIT = 4;

export const CAMPAIGN_ATTESTATION_NONCE_BYTES = 16;
export const CAMPAIGN_MIN_REWARD_MIST = 1;
export const CAMPAIGN_MAX_REWARD_MIST = 100_000_000_000;
export const CAMPAIGN_MAX_CLAIMS = 1_000_000;
export const CAMPAIGN_MIN_DURATION_MS = 3_600_000;
export const CAMPAIGN_MAX_DURATION_MS = 31_536_000_000;
export const CAMPAIGN_VIEW_REQUIRED_SECONDS = Number(
  process.env.NEXT_PUBLIC_REWARD_VIEW_REQUIRED_SECONDS ?? '30'
);
